[package]
name = "wc-rs"
version = "0.1.0"
authors = ["daniel <daniel@nopemail.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1

[dependencies]
rayon = "1.5.0"
